### ISSUE TITLE
Mention briefly what an RDD is?

### ISSUE THREAD

**Issue by DuskEagle** [sjbrunst/spark-repartition#1]
I think just a couple sentences should suffice. A lot of people don't know anything about Spark and the opening paragraphs briefly introduce them to it, so might as well clear up the terminology before it gets used later in the piece.

**Comment by sjbrunst** [comment]
Good idea. I'll add it to the opening section.

**Comment by sjbrunst** [comment]
How does it look now? (Github auto-closed, but feel free to reopen if it needs more.)
